<?php

/**
 * Title: MuseumPath - Banner 1 (Grow Your IT Business)
 * Slug: museumpath/banner-1
 * Categories: call-to-action
 * Viewport Width: 1280
 */

?>

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg":"dark","text_color":"white","mb_lg":"","pt_lg":"7","pr_lg":"5","pb_lg":"7","pl_lg":"5","border":"0","rounded_size":"0","sd_shortcode":"[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='dark'  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='7'  pr_lg='5'  pb_lg='7'  pl_lg='5'  border='0'  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size='0'  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-7 pe-5 pb-7 ps-5 border-0 rounded-0 bg-dark bg-image-fixed text-white container-fluid"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"Plan Your Museum Journey","html_tag":"h2","text_color":"primary","text_color_custom":"#0c0d24","font_size":"display-3","font_weight":"font-weight-bold","text_align_lg":"text-lg-center"} -->
<h2 class="wp-block-blockstrap-blockstrap-widget-heading mb-3 text-primary text-center font-weight-bold display-3">Plan Your Museum Journey</h2>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"From tickets to travel tips, make your visit seamless and unforgettable.","html_tag":"p","text_color":"gray-dark","font_size":"fs-5","font_weight":"font-weight-normal","text_align_lg":"text-lg-center","mt":"3","mb":"4","mr_md":"0","ml_md":"0","mt_lg":"3","mb_lg":"4"} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mt-3 mb-4 me-md-0 ms-md-0 mt-lg-3 mb-lg-4 text-gray-dark text-center font-weight-normal fs-5">From tickets to travel tips, make your visit seamless and unforgettable.</p>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-container {"display_lg":"d-lg-flex","flex_justify_content_lg":"justify-content-lg-center","sd_shortcode":"[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg='d-lg-flex'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg='justify-content-lg-center'  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container mb-3 bg-image-fixed d-flex container justify-content-center"><!-- wp:blockstrap/blockstrap-widget-button {"text":"Start Planning","icon_class":"fa-solid fa-arrow-right","icon_position":"right","text_color":"dark","bg_hover":"transparent","text_color_hover":"primary","font_case":"text-uppercase","pt_lg":"3","pb_lg":"3","styleid":"block-fvmhrxmp5w","content":"\u003ca   class=\u0022btn btn-primary text-dark pt-3 pb-3 text-dark text-uppercase block-fvmhrxmp5w\u0022\u003eStart Planning\u003ci class=\u0022fa-solid fa-arrow-right ms-2\u0022\u003e\u003c/i\u003e\u003c/a\u003e \u003cstyle\u003ehtml .editor-styles-wrapper .block-fvmhrxmp5w:hover {color: var(\u002d\u002dwp\u002d\u002dpreset\u002d\u002dcolor\u002d\u002dprimary) !important;} html .editor-styles-wrapper .block-fvmhrxmp5w:hover {background: var(\u002d\u002dwp\u002d\u002dpreset\u002d\u002dcolor\u002d\u002dtransparent) !important;} html .editor-styles-wrapper .block-fvmhrxmp5w.btn:hover {border-color: var(\u002d\u002dwp\u002d\u002dpreset\u002d\u002dcolor\u002d\u002dtransparent) !important;} \u003c/style\u003e","sd_shortcode":"[bs_button type='home'  page_id=''  meta_key=''  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='Start Planning'  icon_class='fa-solid fa-arrow-right'  icon_position='right'  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type='btn'  link_size=''  link_bg='primary'  link_bg_color='#0073aa'  link_bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  text_color='dark'  text_color_custom=''  bg_hover='transparent'  bg_hover_color='#0073aa'  bg_hover_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  text_color_hover='primary'  text_color_hover_custom=''  font_size_custom=''  font_weight=''  font_case='text-uppercase'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='3'  pr_lg=''  pb_lg='3'  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  display=''  display_md=''  display_lg=''  visibility_conditions=''  css_class=''  styleid='block-fvmhrxmp5w' ]"} /--></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->