<?php

/**
 * Title: MuseumPath - Default Header
 * Slug: museumpath/header-default
 * Categories: blockstrap-site-header
 * Viewport Width: 1280
 */
$logo_url = esc_url(get_theme_file_uri('assets/images/logo-color.svg')); /* <?php echo esc_url( $logo_url ); ?> */

?>

<!-- wp:blockstrap/blockstrap-widget-skip-links {"content":"\u003ca href=\u0022#main\u0022 class=\u0022btn btn-primary\u0022\u003eSkip to main content\u003c/a\u003e","sd_shortcode":"[bs_skip_links text1='Skip to main content'  hash1='main'  text2=''  hash2=''  text3=''  hash3=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg_color":"#00224f","mt":"0","mb_lg":"","pr":"0","pl":"0","pt_lg":"3","pr_lg":"3","pl_lg":"3","border":"0","rounded":"rounded","sd_shortcode":"[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#00224f'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt='0'  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr='0'  pb=''  pl='0'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='3'  pr_lg='3'  pb_lg=''  pl_lg='3'  border='0'  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container mt-0 pe-0 ps-0 pt-3 pe-lg-3 ps-lg-3 border-0 bg-image-fixed container-fluid rounded"><!-- wp:blockstrap/blockstrap-widget-navbar {"bg":"dark","bg_color":"#00224f","container":"navbar-dark","mb_lg":"","pr":"3","pr_lg":"4","pl_lg":"3","border":"0","sd_shortcode":"[bs_navbar bg='dark'  bg_color='#00224f'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bgtus='false'  cscos='false'  container='navbar-dark'  inner_container='container-fluid px-0'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr='3'  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg='4'  pb_lg=''  pl_lg='3'  border='0'  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom='' ]","sd_shortcode_close":"[/bs_navbar]"} -->
<nav class="navbar navbar-expand-lg pe-3 pe-lg-4 ps-3 border-0 bg-dark bg-image-fixed navbar-dark"><div class="wp-block-blockstrap-blockstrap-widget-navbar container-fluid px-0"><!-- wp:blockstrap/blockstrap-widget-navbar-brand {"text":"","icon_image":"<?php echo esc_url( $logo_url ); ?>","img_max_width":190,"custom_url":"/","brand_font_size":"h1","brand_font_weight":"font-weight-normal","brand_font_italic":"font-italic","bg_gradient":"linear-gradient(135deg,rgb(34,227,7) 0%,rgb(245,245,245) 100%)","bg_on_text":true,"mb_lg":"","pt_lg":"3","pb_lg":"3","pl_lg":"3","rounded_size":"lg","sd_shortcode":"[bs_navbar_brand text=''  icon_image='<?php echo esc_url( $logo_url ); ?>'  img_max_width='190'  type='home'  custom_url='/'  text_color=''  brand_font_size='h1'  brand_font_weight='font-weight-normal'  brand_font_italic='font-italic'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgb(34,227,7) 0%,rgb(245,245,245) 100%)'  bg_on_text='true'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='3'  pr_lg=''  pb_lg='3'  pl_lg='3'  border=''  rounded=''  rounded_size='lg'  shadow=''  css_class='' ]"} -->
<a class="navbar-brand d-flex align-items-center pt-3 pb-3 ps-3 rounded-lg" href="http://museumpath.local"><img class="" alt="Site logo" src="<?php echo esc_url( $logo_url ); ?>" style="max-width:190px" width="190" height="50"/><span class="mb-0 props.attributes.brand_font_size props.attributes.brand_font_weight fst-italic"></span></a>
<!-- /wp:blockstrap/blockstrap-widget-navbar-brand -->

<!-- wp:blockstrap/blockstrap-widget-nav {"anchor":"main-nav","flex_justify_content_lg":"justify-content-lg-end","font_size":"fs-6","ml_lg":"","rounded_size":"lg","width":"w-100","sd_shortcode":"[bs_nav anchor='main-nav'  inside_navbar='1'  container=''  flex_direction=''  nav_style=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg='justify-content-lg-end'  nav_fill=''  font_size='fs-6'  font_size_custom=''  bg=''  mt=''  mr='auto'  mb=''  ml='auto'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg='0'  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size='lg'  shadow=''  width='w-100'  css_class='' ]","sd_shortcode_close":"[/bs_nav]"} -->
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav_main-nav" aria-label="Open menu"><span class="navbar-toggler-icon"></span></button><div class="wp-block-blockstrap-blockstrap-widget-nav blockstrap-nav collapse navbar-collapse" id="navbarNav_main-nav"><ul class="wp-block-blockstrap-blockstrap-widget-nav navbar-nav me-auto ms-auto me-lg-0 rounded-lg w-100 fs-6 justify-content-end"><!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"gd_place","page_id":"1858","custom_url":"#about","text":"Explore","text_color":"white","pr_lg":"2","pl_lg":"2","content":"\u003ca href=\u0022#http://museumpath.local/place/\u0022 class=\u0022nav-link link-white \u0022 \u003eExplore\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='gd_place'  page_id='1858'  post_id=''  taxonomy=''  term_id=''  custom_url='#about'  text='Explore'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg='2'  pb_lg=''  pl_lg='2'  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"3336","custom_url":"#about","text":"Blog","text_color":"white","pr_lg":"2","pl_lg":"2","content":"\u003ca href=\u0022#http://museumpath.local/blog/\u0022 class=\u0022nav-link link-white \u0022 \u003eBlog\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='page'  page_id='3336'  post_id=''  taxonomy=''  term_id=''  custom_url='#about'  text='Blog'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg='2'  pb_lg=''  pl_lg='2'  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"4426","custom_url":"#about","text":"Add Listing","icon_class":"fa-solid fa-plus","link_size":"large","link_bg":"outline-white","text_color":"white","font_weight":"font-weight-bold","pr_lg":"2","pl_lg":"2","content":"\u003ca href=\u0022#http://museumpath.local/add-listing/\u0022 class=\u0022nav-link link-white fw-bold\u0022 \u003e\u003ci class=\u0022fa-solid fa-plus me-2\u0022\u003e\u003c/i\u003eAdd Listing\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='page'  page_id='4426'  post_id=''  taxonomy=''  term_id=''  custom_url='#about'  text='Add Listing'  icon_class='fa-solid fa-plus'  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size='large'  link_bg='outline-white'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-bold'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg='2'  pb_lg=''  pl_lg='2'  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"uwp_account","custom_url":"#","text":"Account","icon_class":"fa-regular fa-user","text_color":"white","pr_lg":"0","pl_lg":"2","content":"\u003ca href=\u0022#http://museumpath.local/account/\u0022 class=\u0022nav-link link-white \u0022 \u003e\u003ci class=\u0022fa-regular fa-user me-2\u0022\u003e\u003c/i\u003eAccount\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='uwp_account'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url='#'  text='Account'  icon_class='fa-regular fa-user'  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg='0'  pb_lg=''  pl_lg='2'  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /--></ul></div>
<!-- /wp:blockstrap/blockstrap-widget-nav --></div></nav>
<!-- /wp:blockstrap/blockstrap-widget-navbar --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->