<?php

/**
 * Title: MuseumPath - Testimonials.
 * Slug: museumpath/testimonials
 * Categories: blockstrap-page-content
 * Viewport Width: 1280
 */

$testimonial_1 = esc_url(get_theme_file_uri('assets/images/demo/testimonial-1.png')); /* <?php echo esc_url( $testimonial_1 ); ?> */
$testimonial_2 = esc_url(get_theme_file_uri('assets/images/demo/testimonial-2.png')); /* <?php echo esc_url( $testimonial_2 ); ?> */
$testimonial_3 = esc_url(get_theme_file_uri('assets/images/demo/testimonial-3.png')); /* <?php echo esc_url( $testimonial_3 ); ?> */
$testimonial_4 = esc_url(get_theme_file_uri('assets/images/demo/testimonial-4.png')); /* <?php echo esc_url( $testimonial_4 ); ?> */

?>

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg_color":"rgba(219,53,69,0.27)","bg_image_fixed":true,"mb_lg":"","pt":"0","pb":"0","pt_lg":"5","pb_lg":"5","position":"position-relative","sd_shortcode":"[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='rgba(219,53,69,0.27)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='true'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='0'  pr=''  pb='0'  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='5'  pr_lg=''  pb_lg='5'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-0 pb-0 pt-lg-5 pb-lg-5 bg-image-fixed container-fluid position-relative"><!-- wp:blockstrap/blockstrap-widget-container {"bg_color":"rgba(255,248,247,0.65)","mb_lg":"","pr_lg":"0","pl_lg":"0","position":"position-relative","sd_shortcode":"[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='rgba(255,248,247,0.65)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg='0'  pb_lg=''  pl_lg='0'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]","metadata":{"name":""}} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pe-0 ps-0 bg-image-fixed container position-relative"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","text_align_lg":"text-lg-center","mb_lg":"","pb":"0","pb_lg":"4","flex_justify_content_lg":"justify-content-lg-center","sd_shortcode":"[bs_container container='row'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-center'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb='0'  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg='4'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg='justify-content-lg-center'  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pb-0 pb-lg-4 bg-image-fixed text-center row justify-content-center"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","text_align_lg":"text-lg-start","mb_lg":"","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-start'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container bg-image-fixed text-start col"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"Hear from explorers who have discovered culture through MuseumPath.","html_tag":"p","text_color":"gray-dark","font_size":"fs-4","font_weight":"font-weight-normal","text_align_lg":"text-lg-start","mb":"2","mb_lg":"2"} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mb-2 mb-lg-2 text-gray-dark text-start font-weight-normal fs-4">Hear from explorers who have discovered culture through MuseumPath.</p>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"What Visitors Are Saying","html_tag":"h2","text_color":"primary","font_size":"display-3","font_weight":"font-weight-bold","text_align_lg":"text-lg-start","mb":"2","mb_lg":"0"} -->
<h2 class="wp-block-blockstrap-blockstrap-widget-heading mb-2 mb-lg-0 text-primary text-start font-weight-bold display-3">What Visitors Are Saying</h2>
<!-- /wp:blockstrap/blockstrap-widget-heading --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"row","row_cols":"1","row_cols_md":"2","row_cols_lg":"2","mb_lg":"","sd_shortcode":"[bs_container container='row'  h100=''  row_cols='1'  row_cols_md='2'  row_cols_lg='2'  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container row-cols-1 row-cols-md-2 row-cols-lg-2 bg-image-fixed row"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","mb_lg":"","pr":"3","pl":"3","pt_lg":"3","pr_lg":"4","pb_lg":"3","pl_lg":"4","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr='3'  pb=''  pl='3'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='3'  pr_lg='4'  pb_lg='3'  pl_lg='4'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pe-3 ps-3 pt-3 pe-lg-4 pb-3 ps-lg-4 bg-image-fixed col"><!-- wp:blockstrap/blockstrap-widget-container {"bg":"dark","bg_color":"rgba(252,252,252,0.13)","pr":"4","pb":"3","pl":"4","pt_lg":"5","pr_lg":"5","pb_lg":"5","pl_lg":"5","sd_shortcode":"[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='dark'  bg_color='rgba(252,252,252,0.13)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr='4'  pb='3'  pl='4'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='5'  pr_lg='5'  pb_lg='5'  pl_lg='5'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container mb-3 pe-4 pb-3 ps-4 pt-5 pe-lg-5 pb-lg-5 ps-lg-5 bg-dark bg-image-fixed container"><!-- wp:image {"id":5316,"width":"130px","height":"130px","scale":"cover","sizeSlug":"full","linkDestination":"none","style":{"border":{"radius":"80px"}}} -->
<figure class="wp-block-image size-full is-resized has-custom-border"><img src="<?php echo esc_url( $testimonial_1 ); ?> " alt="" class="wp-image-5316" style="border-radius:80px;object-fit:cover;width:130px;height:130px"/></figure>
<!-- /wp:image -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"James T., Traveler","html_tag":"h6","text_color":"white","font_size":"h4","font_weight":"font-weight-bolder","mb_lg":"0"} -->
<h6 class="wp-block-blockstrap-blockstrap-widget-heading mb-0 text-white font-weight-bolder h4">James T., Traveler</h6>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"\u0022 MuseumPath helped me discover hidden cultural gems I never knew existed. It’s like having a personal guide to the world’s history. \u0022","html_tag":"p","text_color":"white","font_size":"fs-5","font_weight":"font-italic","mt_lg":"3","mb_lg":""} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mt-3 text-white font-italic fs-5">" MuseumPath helped me discover hidden cultural gems I never knew existed. It’s like having a personal guide to the world’s history. "</p>
<!-- /wp:blockstrap/blockstrap-widget-heading --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","mb_lg":"","pt":"0","pr":"3","pl":"3","pt_lg":"3","pr_lg":"4","pb_lg":"3","pl_lg":"4","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='0'  pr='3'  pb=''  pl='3'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='3'  pr_lg='4'  pb_lg='3'  pl_lg='4'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-0 pe-3 ps-3 pt-lg-3 pe-lg-4 pb-3 ps-lg-4 bg-image-fixed col"><!-- wp:blockstrap/blockstrap-widget-container {"bg":"dark","bg_color":"rgba(143,43,43,0.15)","pr":"4","pb":"3","pl":"4","pt_lg":"5","pr_lg":"5","pb_lg":"5","pl_lg":"5","sd_shortcode":"[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='dark'  bg_color='rgba(143,43,43,0.15)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr='4'  pb='3'  pl='4'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='5'  pr_lg='5'  pb_lg='5'  pl_lg='5'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container mb-3 pe-4 pb-3 ps-4 pt-5 pe-lg-5 pb-lg-5 ps-lg-5 bg-dark bg-image-fixed container"><!-- wp:image {"id":5319,"width":"130px","height":"130px","scale":"cover","sizeSlug":"full","linkDestination":"none","style":{"border":{"radius":"80px"}}} -->
<figure class="wp-block-image size-full is-resized has-custom-border"><img src="<?php echo esc_url( $testimonial_2 ); ?> " alt="" class="wp-image-5319" style="border-radius:80px;object-fit:cover;width:130px;height:130px"/></figure>
<!-- /wp:image -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Marcus R., History Enthusiast","html_tag":"h6","text_color":"white","font_size":"h4","font_weight":"font-weight-bolder","mb_lg":"0"} -->
<h6 class="wp-block-blockstrap-blockstrap-widget-heading mb-0 text-white font-weight-bolder h4">Marcus R., History Enthusiast</h6>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"\u0022 From ancient ruins to modern art, MuseumPath makes it easy to plan and explore the best museums across the globe. \u0022","html_tag":"p","text_color":"white","font_size":"fs-5","font_weight":"font-italic","mt_lg":"3","mb_lg":""} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mt-3 text-white font-italic fs-5">" From ancient ruins to modern art, MuseumPath makes it easy to plan and explore the best museums across the globe. "</p>
<!-- /wp:blockstrap/blockstrap-widget-heading --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","mb_lg":"","pt":"0","pr":"3","pl":"3","pt_lg":"3","pr_lg":"4","pb_lg":"3","pl_lg":"4","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='0'  pr='3'  pb=''  pl='3'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='3'  pr_lg='4'  pb_lg='3'  pl_lg='4'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-0 pe-3 ps-3 pt-lg-3 pe-lg-4 pb-3 ps-lg-4 bg-image-fixed col"><!-- wp:blockstrap/blockstrap-widget-container {"bg":"dark","bg_color":"rgba(143,43,43,0.15)","pr":"4","pb":"3","pl":"4","pt_lg":"5","pr_lg":"5","pb_lg":"5","pl_lg":"5","sd_shortcode":"[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='dark'  bg_color='rgba(143,43,43,0.15)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr='4'  pb='3'  pl='4'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='5'  pr_lg='5'  pb_lg='5'  pl_lg='5'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container mb-3 pe-4 pb-3 ps-4 pt-5 pe-lg-5 pb-lg-5 ps-lg-5 bg-dark bg-image-fixed container"><!-- wp:image {"id":5317,"width":"130px","height":"130px","scale":"cover","sizeSlug":"full","linkDestination":"none","style":{"border":{"radius":"80px"}}} -->
<figure class="wp-block-image size-full is-resized has-custom-border"><img src="<?php echo esc_url( $testimonial_3 ); ?> " alt="" class="wp-image-5317" style="border-radius:80px;object-fit:cover;width:130px;height:130px"/></figure>
<!-- /wp:image -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Daniel L., Educator","html_tag":"h6","text_color":"white","font_size":"h4","font_weight":"font-weight-bolder","mb_lg":"0"} -->
<h6 class="wp-block-blockstrap-blockstrap-widget-heading mb-0 text-white font-weight-bolder h4">Daniel L., Educator</h6>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"\u0022 I use MuseumPath to design immersive learning trips for my students. It’s an invaluable resource for cultural education. \u0022","html_tag":"p","text_color":"white","font_size":"fs-5","font_weight":"font-italic","mt_lg":"3","mb_lg":""} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mt-3 text-white font-italic fs-5">" I use MuseumPath to design immersive learning trips for my students. It’s an invaluable resource for cultural education. "</p>
<!-- /wp:blockstrap/blockstrap-widget-heading --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","mb_lg":"","pt":"0","pr":"3","pl":"3","pt_lg":"3","pr_lg":"4","pb_lg":"3","pl_lg":"4","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='0'  pr='3'  pb=''  pl='3'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='3'  pr_lg='4'  pb_lg='3'  pl_lg='4'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-0 pe-3 ps-3 pt-lg-3 pe-lg-4 pb-3 ps-lg-4 bg-image-fixed col"><!-- wp:blockstrap/blockstrap-widget-container {"bg":"dark","bg_color":"rgba(252,252,252,0.13)","pr":"4","pb":"3","pl":"4","pt_lg":"5","pr_lg":"5","pb_lg":"5","pl_lg":"5","sd_shortcode":"[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='dark'  bg_color='rgba(252,252,252,0.13)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr='4'  pb='3'  pl='4'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='5'  pr_lg='5'  pb_lg='5'  pl_lg='5'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container mb-3 pe-4 pb-3 ps-4 pt-5 pe-lg-5 pb-lg-5 ps-lg-5 bg-dark bg-image-fixed container"><!-- wp:image {"id":5318,"width":"130px","height":"130px","scale":"cover","sizeSlug":"full","linkDestination":"none","style":{"border":{"radius":"80px"}}} -->
<figure class="wp-block-image size-full is-resized has-custom-border"><img src="<?php echo esc_url( $testimonial_4 ); ?> " alt="" class="wp-image-5318" style="border-radius:80px;object-fit:cover;width:130px;height:130px"/></figure>
<!-- /wp:image -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Samuel K., Frequent Traveler","html_tag":"h6","text_color":"white","font_size":"h4","font_weight":"font-weight-bolder","mb_lg":"0"} -->
<h6 class="wp-block-blockstrap-blockstrap-widget-heading mb-0 text-white font-weight-bolder h4">Samuel K., Frequent Traveler</h6>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"\u0022 Whether I’m at home or abroad, MuseumPath always leads me to meaningful exhibits that deepen my understanding of history. \u0022","html_tag":"p","text_color":"white","font_size":"fs-5","font_weight":"font-italic","mt_lg":"3","mb_lg":""} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mt-3 text-white font-italic fs-5">" Whether I’m at home or abroad, MuseumPath always leads me to meaningful exhibits that deepen my understanding of history. "</p>
<!-- /wp:blockstrap/blockstrap-widget-heading --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->